import { validatePreviewUrl } from '@sanity/preview-url-secret'
import { draftMode } from 'next/headers'
import { redirect } from 'next/navigation'
import { client } from '@/lib/sanity'

/**
 * Enables Next.js Draft Mode after validating a one-time preview secret
 * generated by the Studio "Preview" action. Redirects to the post on the
 * live site, where it renders the draft/scheduled content.
 */
const token = process.env.SANITY_API_READ_TOKEN

export async function GET(request: Request) {
  if (!client || !token) {
    return new Response('Preview is not configured', { status: 500 })
  }

  const { isValid, redirectTo = '/' } = await validatePreviewUrl(
    client.withConfig({ token }),
    request.url
  )

  if (!isValid) {
    return new Response('Invalid or expired preview link', { status: 401 })
  }

  draftMode().enable()
  redirect(redirectTo)
}
